# Generated by Django 4.0 on 2022-10-18 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionAsociados', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DatosAccidentes',
        ),
        migrations.RenameField(
            model_name='datoscoop',
            old_name='autos_numero',
            new_name='aniosFuncionando_numero',
        ),
        migrations.RenameField(
            model_name='datoscoop',
            old_name='personas_afectadas',
            new_name='numeroEmpleados_numero',
        ),
        migrations.RenameField(
            model_name='datoscoop',
            old_name='calle_text',
            new_name='numeroRegistro_text',
        ),
        migrations.AddField(
            model_name='datoscoop',
            name='logo_img',
            field=models.ImageField(default=int, upload_to=''),
            preserve_default=False,
        ),
    ]
