# Generated by Django 4.0 on 2022-10-18 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionAsociados', '0002_delete_datosaccidentes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datoscoop',
            name='logo_img',
            field=models.BinaryField(default=b'0', max_length=50000000),
        ),
    ]
