# Generated by Django 4.0 on 2022-10-18 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestionAsociados', '0003_alter_datoscoop_logo_img'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DatosCoop',
        ),
    ]
