# Generated by Django 4.1.1 on 2022-10-21 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0002_administrador_aspirante_cajero_jefeoperaciones_and_more'),
        ('gestionAsociados', '0004_delete_datoscoop'),
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=8)),
                ('nombre', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=8)),
                ('nombre', models.CharField(max_length=30)),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionAsociados.departamento')),
            ],
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=5)),
                ('nombre', models.CharField(max_length=30)),
                ('extensionTelefono', models.CharField(blank=True, max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='PeticionAdmision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre1', models.CharField(max_length=30)),
                ('nombre2', models.CharField(max_length=30)),
                ('nombre3', models.CharField(blank=True, max_length=30)),
                ('apellido1', models.CharField(max_length=30)),
                ('apellido2', models.CharField(blank=True, max_length=30)),
                ('fechaNac', models.DateField()),
                ('lugarNac', models.CharField(max_length=150)),
                ('direccion', models.CharField(max_length=250)),
                ('email', models.EmailField(max_length=254)),
                ('personasDependientes', models.IntegerField()),
                ('verificada', models.BooleanField(blank=True, default=False)),
                ('aprobada', models.BooleanField(blank=True, default=False)),
                ('estado', models.BooleanField(blank=True, default=False)),
                ('aspirante', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='user.aspirante')),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionAsociados.departamento')),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionAsociados.municipio')),
                ('pais', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionAsociados.pais')),
            ],
        ),
        migrations.CreateModel(
            name='TipoDocIdentidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreDocumento', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Vivienda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('propietario', models.CharField(blank=True, max_length=30)),
                ('parentesco', models.CharField(max_length=20)),
                ('tenenciaVivienda', models.CharField(max_length=30)),
                ('tiempo', models.IntegerField()),
                ('ubicacion', models.CharField(blank=True, max_length=150)),
                ('peticionAdmision', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='gestionAsociados.peticionadmision')),
            ],
        ),
        migrations.CreateModel(
            name='Trabajo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=30)),
                ('lugarTrabajo', models.CharField(max_length=30)),
                ('direccion', models.CharField(max_length=250)),
                ('telefono', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('sueldo', models.DecimalField(decimal_places=4, max_digits=10)),
                ('cargo', models.CharField(max_length=30)),
                ('jefe', models.CharField(max_length=30)),
                ('peticionAdmision', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='gestionAsociados.peticionadmision')),
            ],
        ),
        migrations.CreateModel(
            name='ReferenciaPersonal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=30)),
                ('telefono', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('peticionAdmision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionAsociados.peticionadmision')),
            ],
        ),
        migrations.CreateModel(
            name='Negocio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreNegocio', models.CharField(max_length=30)),
                ('direccion', models.CharField(max_length=250)),
                ('telefono', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('numRegistroIva', models.CharField(max_length=50)),
                ('giro', models.CharField(max_length=150)),
                ('numTrabajadores', models.IntegerField()),
                ('capital', models.DecimalField(decimal_places=4, max_digits=13)),
                ('mercancia', models.DecimalField(decimal_places=4, max_digits=13)),
                ('mobiliarioEquipo', models.DecimalField(decimal_places=4, max_digits=13)),
                ('peticionAdmision', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='gestionAsociados.peticionadmision')),
            ],
        ),
        migrations.CreateModel(
            name='Familiar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parentesco', models.CharField(max_length=20)),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=30)),
                ('telefono', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionAsociados.departamento')),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionAsociados.municipio')),
                ('peticionAdmision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionAsociados.peticionadmision')),
            ],
        ),
        migrations.CreateModel(
            name='DocIdentidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=30)),
                ('peticionAdmision', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='gestionAsociados.peticionadmision')),
                ('tipoDoc', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='gestionAsociados.tipodocidentidad')),
            ],
        ),
        migrations.CreateModel(
            name='DocAnexo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('doc', models.FileField(blank=True, upload_to='')),
                ('peticionAdmision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionAsociados.peticionadmision')),
            ],
        ),
        migrations.CreateModel(
            name='Conyuge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=30)),
                ('docIdentidad', models.CharField(max_length=15)),
                ('telefono', models.CharField(max_length=15)),
                ('peticionAdmision', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='gestionAsociados.peticionadmision')),
            ],
        ),
        migrations.CreateModel(
            name='Beneficiario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parentesco', models.CharField(max_length=20)),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=30)),
                ('beneficio', models.DecimalField(decimal_places=4, max_digits=12)),
                ('peticionAdmision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionAsociados.peticionadmision')),
            ],
        ),
        migrations.CreateModel(
            name='Asociacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('descripcion', models.CharField(max_length=250)),
                ('peticionAdmision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionAsociados.peticionadmision')),
            ],
        ),
    ]
