# Generated by Django 4.1.1 on 2022-10-21 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cobros', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cuotas',
            new_name='Cuota',
        ),
    ]
