# Generated by Django 4.1.1 on 2022-10-22 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cobros', '0002_rename_cuotas_cuota'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuota',
            name='fecha_fin',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='cuota',
            name='fecha_inicio',
            field=models.DateField(null=True),
        ),
    ]
