# Generated by Django 4.1.1 on 2022-11-04 16:49

import directivos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreRepresentante', models.TextField(max_length=200)),
                ('cargo', models.TextField(max_length=100)),
                ('firma', models.ImageField(blank=True, null=True, upload_to=directivos.models.filepath)),
            ],
        ),
    ]
