# Generated by Django 4.1.1 on 2022-11-04 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directivos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='cargo',
            field=models.TextField(choices=[('Presidente', 'Presidente'), ('Secretario', 'Secretario')]),
        ),
    ]
