# Generated by Django 4.0 on 2022-10-18 16:15

from django.db import migrations, models
import gestionCooperativa.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DatosCoop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_text', models.CharField(max_length=200)),
                ('departamento_text', models.CharField(max_length=200)),
                ('municipio_text', models.CharField(max_length=200)),
                ('numeroRegistro_text', models.CharField(max_length=200)),
                ('aniosFuncionando_numero', models.IntegerField()),
                ('numeroEmpleados_numero', models.IntegerField()),
                ('descripcion_text', models.CharField(max_length=200)),
                ('logo_img', models.ImageField(blank=True, null=True, upload_to=gestionCooperativa.models.filepath)),
            ],
        ),
    ]
